kubeVersion: ">=1.24.0-0"
apiVersion: v2
name: qbittorrent
version: 18.1.6
appVersion: 4.6.2
description: qBittorrent is a cross-platform free and open-source BitTorrent client
home: https://hotio.dev/containers/qbittorrent/
icon: https://truecharts.org/img/hotlink-ok/chart-icons/qbittorrent.png
deprecated: false
sources:
  - https://github.com/hotio/qbittorrent/tree/release
  - https://github.com/jfroy/truenasapps
  - https://github.com/truecharts/charts/tree/master/charts/stable/qbittorrent
maintainers:
  - name: Jean-Francois Roy
    email: jf@devklog.net
    url: https://github.com/jfroy
keywords:
  - qbittorrent
  - torrrent
  - vuetorrent
dependencies:
  - name: common
    version: 17.2.22
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
annotations:
  max_scale_version: 23.10.2
  min_scale_version: 23.10.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.13"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
type: application
