apiVersion: v2
appVersion: "2.8.3"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.0.9
deprecated: false
description: "Docker Registry is used to store and distribute Docker images using HTTP API. This allows you host your own private Registry and store your images. Uses official Chart Registry image @ https://hub.Chart.com/_/registry/\n"
home: https://truecharts.org/charts/incubator/dockerregistry
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dockerregistry.png
keywords:
  - dockerregistry
  - Cloud
  - Network-Management
  - Productivity
  - Tools-Utilities
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: jf@devklog.net
    name: Jean-Francois Roy
    url: https://github.com/jfroy/truenasapps
name: dockerregistry
sources:
  - https://github.com/jfroy/truenasapps
  - https://github.com/distribution/distribution
  - https://registry.hub.docker.com/_/registry/
type: application
version: 3.0.1
