image:
  pullPolicy: IfNotPresent
  repository: docker.io/registry
  tag: 2.8.3@sha256:c7e7796afbd3178fa965bff101e3a24ff5d024aea329c8cd66c213b6a99a644e
service:
  main:
    ports:
      main:
        port: 5000
        targetPort: 5000
persistence:
  datastoragepath:
    enabled: true
    mountPath: /var/lib/registry
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
portal:
  open:
    enabled: true
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
